---
title: "HW5"
author: "Hannah Boyd"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
library(dplyr)
```

# Question 1

```{r}
set.seed(seed=1)
sample <- rnorm(n=5)
sample
sqrt(length(sample))*(mean(sample))/sd(sample)
```
**Answer: The value of t is 0.3007746**

# Question 2

```{r}
set.seed(seed=1)
mc <- replicate(1000, t.test(rnorm(n=5))$statistic)
mean(mc)
sd(mc)
length(which(mc > 2))/1000
```

**Answer: 6.8% of generated test-statistics are larger than 2**

# Question 3

```{r}
1- pt(2, df =5 -1)
ps = seq(1/(100+1), 1 -1/(100+1), len =100)
qt(ps, df=5-1)
```
## Part A

```{r}
Ns<-seq(5,30,30)
B <- 1000
LIM <- c(-4.5,4.5)
for(N in Ns){
	ts <- replicate(B,{
    x <- rnorm(N)
    y <- rnorm(N)
    t.test(x,y, var.equal = TRUE)$stat
    })
  ps <- seq(1/(B+1),1-1/(B+1),len=B)
  qqplot(qt(ps,df=2*N-2),ts,main=N,
         xlab="Theoretical",ylab="Observed",
         xlim=LIM, ylim=LIM)
  abline(0,1)
}  
```



## Part B

```{r}
Ns<-seq(30,30,30)
B <- 1000
LIM <- c(-4.5,4.5)
for(N in Ns){
	ts <- replicate(B,{
    x <- rnorm(N)
    y <- rnorm(N)
    t.test(x,y, var.equal = TRUE)$stat
    })
  ps <- seq(1/(B+1),1-1/(B+1),len=B)
  qqplot(qt(ps,df=2*N-2),ts,main=N,
         xlab="Theoretical",ylab="Observed",
         xlim=LIM, ylim=LIM)
  abline(0,1)
} 
```



## Part C

**C) The approximations are spot on for all sample sizes.**

# Question 4

## Part A

```{r}
set.seed(1)
B=100
ps = seq(1/(B+1), 1-1/(B+1),len=B)
par(mfrow=c(2,2))
for(samplesize in c(5)) {
  mc <- replicate(1000, t.test(rnorm(n=samplesize), rnorm(n=samplesize), var.equal=T)$statistic)
  qqplot(qt(ps,df=2*samplesize-2), qt(mc, df=2*samplesize-2), 
         main=paste("n=",samplesize,sep=""),
         ylim=c(-6,6),
         xlim=c(-6,6))
  abline(0,1)
}
```


## Part B

```{r}
set.seed(1)
B=100
ps = seq(1/(B+1), 1-1/(B+1),len=B)
par(mfrow=c(2,2))
for(samplesize in c(30)) {
  mc <- replicate(1000, t.test(rnorm(n=samplesize), rnorm(n=samplesize), var.equal=T)$statistic)
  qqplot(qt(ps,df=2*samplesize-2), qt(mc, df=2*samplesize-2), 
         main=paste("n=",samplesize,sep=""),
         ylim=c(-6,6),
         xlim=c(-6,6))
  abline(0,1)
}
```


## Part C

**Answer: C) The approximations are spot on for all sample sizes** 


